import { db } from '@/db';
import { product } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // Running Shoes (categoryId: 1) - 5 products
        {
            name: 'Nike Air Zoom Pegasus 40',
            description: 'The Nike Air Zoom Pegasus 40 delivers responsive cushioning and a smooth ride for your daily runs. Features updated React foam and Zoom Air units for superior comfort.',
            price: 129.99,
            stock: 45,
            imageURL: 'https://placehold.co/600x400/png?text=Nike+Air+Zoom+Pegasus',
            categoryId: 1,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Adidas Ultraboost 23',
            description: 'Experience unparalleled energy return with the Adidas Ultraboost 23. Boost midsole technology provides exceptional comfort for long-distance running.',
            price: 189.99,
            stock: 32,
            imageURL: 'https://placehold.co/600x400/png?text=Adidas+Ultraboost',
            categoryId: 1,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Brooks Ghost 15',
            description: 'The Brooks Ghost 15 offers a balanced ride with soft cushioning and smooth transitions. Perfect for neutral runners seeking reliability and comfort.',
            price: 139.99,
            stock: 58,
            imageURL: 'https://placehold.co/600x400/png?text=Brooks+Ghost+15',
            categoryId: 1,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Asics Gel-Kayano 30',
            description: 'Premium stability running shoe with advanced GEL technology for maximum shock absorption. Ideal for overpronators seeking superior support during long runs.',
            price: 169.99,
            stock: 28,
            imageURL: 'https://placehold.co/600x400/png?text=Asics+Gel-Kayano',
            categoryId: 1,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'New Balance Fresh Foam 880v13',
            description: 'Versatile daily trainer featuring Fresh Foam midsole for plush cushioning. Engineered mesh upper provides breathability and a secure fit for all-day comfort.',
            price: 134.99,
            stock: 67,
            imageURL: 'https://placehold.co/600x400/png?text=New+Balance+880',
            categoryId: 1,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Basketball (categoryId: 2) - 4 products
        {
            name: 'Spalding NBA Official Game Ball',
            description: 'The official game ball of the NBA, featuring premium full-grain leather construction. Provides superior grip and durability for professional-level performance.',
            price: 159.99,
            stock: 24,
            imageURL: 'https://placehold.co/600x400/png?text=Spalding+NBA+Ball',
            categoryId: 2,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Nike LeBron Lakers Jersey',
            description: 'Authentic Nike Swingman jersey featuring LeBron James Lakers design. Made with breathable Dri-FIT fabric for comfort during intense games.',
            price: 119.99,
            stock: 18,
            imageURL: 'https://placehold.co/600x400/png?text=Nike+LeBron+Jersey',
            categoryId: 2,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Wilson Evolution Basketball',
            description: 'Premium indoor basketball with composite leather cover. Exclusive cushion core technology ensures consistent bounce and exceptional feel on the court.',
            price: 69.99,
            stock: 42,
            imageURL: 'https://placehold.co/600x400/png?text=Wilson+Evolution',
            categoryId: 2,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Under Armour Curry Flow 10',
            description: 'Signature Stephen Curry basketball shoes featuring UA Flow cushioning technology. Lightweight design provides explosive responsiveness and court feel.',
            price: 149.99,
            stock: 35,
            imageURL: 'https://placehold.co/600x400/png?text=UA+Curry+Flow',
            categoryId: 2,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Football (categoryId: 3) - 3 products
        {
            name: 'Wilson NFL Official Football',
            description: 'Official NFL game ball with premium leather construction and iconic pebble grain texture. Built for superior grip and performance in all weather conditions.',
            price: 129.99,
            stock: 31,
            imageURL: 'https://placehold.co/600x400/png?text=Wilson+NFL+Football',
            categoryId: 3,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Nike Mercurial Vapor 15 Elite',
            description: 'Elite-level soccer cleats designed for explosive speed. Features innovative traction pattern and lightweight construction for maximum agility on the pitch.',
            price: 279.99,
            stock: 22,
            imageURL: 'https://placehold.co/600x400/png?text=Nike+Mercurial',
            categoryId: 3,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Adidas Predator Match Soccer Ball',
            description: 'Professional-grade soccer ball with textured surface for enhanced grip and control. FIFA Quality certified for official match play.',
            price: 39.99,
            stock: 76,
            imageURL: 'https://placehold.co/600x400/png?text=Adidas+Predator+Ball',
            categoryId: 3,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Tennis (categoryId: 4) - 3 products
        {
            name: 'Wilson Pro Staff RF97 Autograph',
            description: 'Roger Federer signature racket with classic feel and precision control. Features braided graphite construction for enhanced stability and power.',
            price: 249.99,
            stock: 15,
            imageURL: 'https://placehold.co/600x400/png?text=Wilson+Pro+Staff',
            categoryId: 4,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Babolat Pure Drive 2023',
            description: 'Modern power racket with enhanced spin potential. FSI Power technology provides explosive power while maintaining excellent control for aggressive baseline play.',
            price: 229.99,
            stock: 19,
            imageURL: 'https://placehold.co/600x400/png?text=Babolat+Pure+Drive',
            categoryId: 4,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Head Championship Tennis Balls',
            description: 'Premium tennis balls with enhanced durability and consistent bounce. USTA and ITF approved for tournament play, perfect for all court surfaces.',
            price: 24.99,
            stock: 93,
            imageURL: 'https://placehold.co/600x400/png?text=Head+Tennis+Balls',
            categoryId: 4,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Fitness Equipment (categoryId: 5) - 4 products
        {
            name: 'Bowflex SelectTech 552 Adjustable Dumbbells',
            description: 'Space-saving adjustable dumbbell set that replaces 15 sets of weights. Adjusts from 5 to 52.5 pounds with quick-turn dial system for seamless weight changes.',
            price: 399.99,
            stock: 12,
            imageURL: 'https://placehold.co/600x400/png?text=Bowflex+Dumbbells',
            categoryId: 5,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Manduka PRO Yoga Mat',
            description: 'Premium yoga mat with superior cushioning and lifetime guarantee. Ultra-dense cushioning provides unparalleled support and joint protection during practice.',
            price: 128.99,
            stock: 48,
            imageURL: 'https://placehold.co/600x400/png?text=Manduka+Yoga+Mat',
            categoryId: 5,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'TRX Pro Suspension Training Kit',
            description: 'Complete bodyweight training system with premium straps and anchor. Includes workout guide and mesh carry bag for portable full-body workouts anywhere.',
            price: 189.99,
            stock: 27,
            imageURL: 'https://placehold.co/600x400/png?text=TRX+Suspension',
            categoryId: 5,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Rogue Fitness Kettlebell 20kg',
            description: 'Cast iron kettlebell with powder coat finish for superior grip. Single-piece construction ensures durability for heavy swings, snatches, and Turkish get-ups.',
            price: 89.99,
            stock: 38,
            imageURL: 'https://placehold.co/600x400/png?text=Kettlebell+20kg',
            categoryId: 5,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Sportswear (categoryId: 6) - 3 products
        {
            name: 'Nike Dri-FIT Legend Training Shirt',
            description: 'Performance training shirt with moisture-wicking Dri-FIT technology. Breathable fabric keeps you cool and dry during intense workouts and training sessions.',
            price: 34.99,
            stock: 84,
            imageURL: 'https://placehold.co/600x400/png?text=Nike+Dri-FIT+Shirt',
            categoryId: 6,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Adidas 4KRFT Sport Shorts',
            description: 'Lightweight training shorts with AEROREADY technology for moisture management. Four-way stretch fabric provides unrestricted movement for all activities.',
            price: 39.99,
            stock: 71,
            imageURL: 'https://placehold.co/600x400/png?text=Adidas+Shorts',
            categoryId: 6,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Under Armour HeatGear Compression Leggings',
            description: 'Compression fit leggings with anti-odor technology and four-way stretch. HeatGear fabric wicks sweat and dries fast for superior comfort during training.',
            price: 54.99,
            stock: 62,
            imageURL: 'https://placehold.co/600x400/png?text=UA+Leggings',
            categoryId: 6,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Accessories (categoryId: 7) - 2 products
        {
            name: 'Hydro Flask Sports Water Bottle 32oz',
            description: 'Insulated stainless steel water bottle keeps drinks cold for 24 hours. BPA-free with leak-proof cap and convenient carry loop for active lifestyles.',
            price: 44.99,
            stock: 95,
            imageURL: 'https://placehold.co/600x400/png?text=Water+Bottle',
            categoryId: 7,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Yonex Premium Gym Towel Set',
            description: 'Microfiber towel set with superior absorbency and quick-dry properties. Includes large workout towel and small face towel, perfect for gym sessions.',
            price: 24.99,
            stock: 78,
            imageURL: 'https://placehold.co/600x400/png?text=Gym+Towel+Set',
            categoryId: 7,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Training Gear (categoryId: 8) - 1 product
        {
            name: 'SKLZ Speed Agility Ladder',
            description: 'Professional training ladder with 15 adjustable rungs for footwork drills. Heavy-duty construction with carry bag included, perfect for speed and agility development.',
            price: 34.99,
            stock: 54,
            imageURL: 'https://placehold.co/600x400/png?text=Agility+Ladder',
            categoryId: 8,
            createdBy: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(product).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});